export interface ICompany {
    id: string; 
    company: string;
    mail: string;
    location: string;
    hrName: string;
    appliedFor: string;
    appliedAt: string;
    created: string;
    contact: string;
  }
  
  export const Companies: ICompany[] = [
    {
      id: '1',
      company: 'ABC',
      mail: 'abc@gmail.com',
      location: 'Indore',
      hrName: 'Aayush',
      appliedFor: 'Back-end',
      appliedAt: '01-02-24',
      created: '01-02-03',
      contact: '+919098546675',
    },
    {
      id: '2',
      company: 'XYZ Solutions',
      mail: 'xyz_solutions@example.com',
      location: 'Mumbai',
      hrName: 'Priya Sharma',
      appliedFor: 'Front-end',
      appliedAt: '15-03-24',
      created: '12-02-23',
      contact: '+919876543210',
    },
    {
      id: '3',
      company: 'Tech Innovators',
      mail: 'tech_innovators@example.com',
      location: 'Bangalore',
      hrName: 'Ravi Kumar',
      appliedFor: 'Full Stack',
      appliedAt: '20-04-24',
      created: '10-01-23',
      contact: '+919123456789',
    },
    {
      id: '4',
      company: 'FutureWorks',
      mail: 'future_works@example.com',
      location: 'Pune',
      hrName: 'Neha Patel',
      appliedFor: 'Data Scientist',
      appliedAt: '05-05-24',
      created: '25-12-22',
      contact: '+919876123456',
    },
    {
      id: '5',
      company: 'GlobalTech',
      mail: 'global_tech@example.com',
      location: 'Hyderabad',
      hrName: 'Anil Mehta',
      appliedFor: 'DevOps',
      appliedAt: '30-06-24',
      created: '01-11-22',
      contact: '+919876654321',
    },
    {
      id: '6',
      company: 'Bright Future Ltd.',
      mail: 'bright_future@example.com',
      location: 'Chennai',
      hrName: 'Mira Singh',
      appliedFor: 'UI/UX Designer',
      appliedAt: '10-07-24',
      created: '15-01-23',
      contact: '+919876789012',
    },
    {
      id: '7',
      company: 'Soft Solutions',
      mail: 'soft_solutions@example.com',
      location: 'Kolkata',
      hrName: 'Suresh Gupta',
      appliedFor: 'Software Engineer',
      appliedAt: '20-08-24',
      created: '20-02-23',
      contact: '+919876543219',
    },
    {
      id: '8',
      company: 'WebWorks',
      mail: 'web_works@example.com',
      location: 'Delhi',
      hrName: 'Anita Raj',
      appliedFor: 'Web Developer',
      appliedAt: '01-09-24',
      created: '11-03-23',
      contact: '+919876542345',
    },
    {
      id: '9',
      company: 'CyberNet',
      mail: 'cyber_net@example.com',
      location: 'Bangalore',
      hrName: 'Deepak Jain',
      appliedFor: 'Security Analyst',
      appliedAt: '15-09-24',
      created: '22-04-23',
      contact: '+919876234567',
    },
    {
      id: '10',
      company: 'CodeCrafters',
      mail: 'code_crafters@example.com',
      location: 'Pune',
      hrName: 'Rakesh Bhatia',
      appliedFor: 'Software Developer',
      appliedAt: '05-10-24',
      created: '10-05-23',
      contact: '+919876345678',
    },
    {
      id: '11',
      company: 'DataPros',
      mail: 'data_pros@example.com',
      location: 'Hyderabad',
      hrName: 'Rohit Verma',
      appliedFor: 'Data Analyst',
      appliedAt: '20-10-24',
      created: '15-06-23',
      contact: '+919876456789',
    },
    {
      id: '12',
      company: 'Innovative Minds',
      mail: 'innovative_minds@example.com',
      location: 'Chennai',
      hrName: 'Sakshi Desai',
      appliedFor: 'Machine Learning Engineer',
      appliedAt: '01-11-24',
      created: '10-07-23',
      contact: '+919876567890',
    },
    {
      id: '13',
      company: 'Tech Titans',
      mail: 'tech_titans@example.com',
      location: 'Mumbai',
      hrName: 'Amit Malhotra',
      appliedFor: 'Systems Engineer',
      appliedAt: '15-11-24',
      created: '20-08-23',
      contact: '+919876678901',
    },
    {
      id: '14',
      company: 'Prime Solutions',
      mail: 'prime_solutions@example.com',
      location: 'Delhi',
      hrName: 'Pooja Shah',
      appliedFor: 'Network Engineer',
      appliedAt: '01-12-24',
      created: '25-09-23',
      contact: '+919876789012',
    },
    {
      id: '15',
      company: 'SmartTech',
      mail: 'smart_tech@example.com',
      location: 'Kolkata',
      hrName: 'Sunil Rao',
      appliedFor: 'Database Administrator',
      appliedAt: '15-12-24',
      created: '30-10-23',
      contact: '+919876890123',
    },
    {
      id: '16',
      company: 'Cloud Solutions',
      mail: 'cloud_solutions@example.com',
      location: 'Bangalore',
      hrName: 'Nikhil Joshi',
      appliedFor: 'Cloud Engineer',
      appliedAt: '01-01-25',
      created: '05-11-23',
      contact: '+919876901234',
    },
    {
      id: '17',
      company: 'DigitalWave',
      mail: 'digital_wave@example.com',
      location: 'Pune',
      hrName: 'Ritu Aggarwal',
      appliedFor: 'Digital Marketer',
      appliedAt: '15-01-25',
      created: '10-12-23',
      contact: '+919877012345',
    },
    {
      id: '18',
      company: 'NextGen Tech',
      mail: 'nextgen_tech@example.com',
      location: 'Hyderabad',
      hrName: 'Vikram Sethi',
      appliedFor: 'Product Manager',
      appliedAt: '01-02-25',
      created: '20-01-24',
      contact: '+919877123456',
    },
    {
      id: '19',
      company: 'AI Innovations',
      mail: 'ai_innovations@example.com',
      location: 'Chennai',
      hrName: 'Karan Kapoor',
      appliedFor: 'AI Engineer',
      appliedAt: '15-02-25',
      created: '30-01-24',
      contact: '+919877234567',
    },
    {
      id: '20',
      company: 'FutureTech',
      mail: 'future_tech@example.com',
      location: 'Mumbai',
      hrName: 'Tina Reddy',
      appliedFor: 'Project Manager',
      appliedAt: '01-03-25',
      created: '10-02-24',
      contact: '+919877345678',
    },
  ];
  
  